import type { RoleDef } from './types'

// Seed data — MC có thể bật/tắt và chỉnh số lượng ở bước setup.
export const BUILT_IN_ROLES: RoleDef[] = [
  {
    id: 'role-cupid',
    name: 'Cupid',
    faction: 'village',
    icon: '💘',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 1,
    targetCount: 2,
    canTargetSelf: true,
    canTargetDead: false,
    effect: 'link',
    firstNightOnly: true,
    extraLives: 0,
    isCouncil: false,
    skippable: false,
    description: 'Chọn 2 người yêu nhau (Cặp đôi) — nếu 1 người chết, người kia cũng chết theo.',
  },
  {
    id: 'role-moonmaiden',
    name: 'Nguyệt Nữ',
    faction: 'village',
    icon: '🌙',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 2,
    targetCount: 1,
    canTargetSelf: false,
    canTargetDead: false,
    effect: 'block',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    skippable: true,
    description:
      'Ngủ với 1 người — người đó bị khóa, hành động đêm nay không có hiệu lực. Nếu ngủ với Sói mà chỉ còn 1 Sói sống thì Sói đó không cắn được ai; nếu còn nhiều Sói thì bầy Sói vẫn cắn bình thường.',
  },
  {
    id: 'role-wolf',
    name: 'Sói',
    faction: 'wolf',
    icon: '🐺',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 3,
    targetCount: 1,
    canTargetSelf: true,
    canTargetDead: false,
    effect: 'kill',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: true,
    skippable: false,
    isWolfBite: true,
    description: 'Cả bầy Sói cùng thức dậy và thống nhất chọn 1 người để cắn — có thể cắn bất kỳ ai, kể cả chính mình.',
  },
  {
    id: 'role-guard',
    name: 'Bảo vệ',
    faction: 'village',
    icon: '🛡️',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 4,
    targetCount: 1,
    canTargetSelf: true,
    canTargetDead: false,
    effect: 'protect',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    skippable: true,
    description: 'Bảo vệ 1 người khỏi bị giết đêm nay. Không nên bảo vệ trùng người 2 đêm liên tiếp.',
  },
  {
    id: 'role-seer',
    name: 'Tiên tri',
    faction: 'village',
    icon: '🔮',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 5,
    targetCount: 1,
    canTargetSelf: false,
    canTargetDead: false,
    effect: 'inspect',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    skippable: true,
    description: 'Soi 1 người để biết có phải phe Sói hay không — MC xem kết quả tại chỗ rồi tự ra dấu hiệu cho người chơi.',
  },
  {
    id: 'role-witch-poison',
    name: 'Phù thủy — Thuốc độc',
    faction: 'village',
    icon: '🧪',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 6,
    targetCount: 1,
    canTargetSelf: true,
    canTargetDead: false,
    effect: 'poison',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    usesPerGame: 1,
    skippable: true,
    description: 'Bình thuốc độc — giết 1 người, bỏ qua mọi bảo vệ. Chỉ dùng được 1 lần trong cả ván.',
  },
  {
    id: 'role-witch-heal',
    name: 'Phù thủy — Thuốc giải',
    faction: 'village',
    icon: '🍵',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 6,
    targetCount: 1,
    canTargetSelf: true,
    canTargetDead: false,
    effect: 'revive',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    usesPerGame: 1,
    skippable: true,
    description: 'Bình thuốc giải — cứu 1 người khỏi chết đêm nay (kể cả người bị Sói cắn). Chỉ dùng được 1 lần trong cả ván. Gán cùng người với "Thuốc độc" để có 1 nhân vật Phù thủy giữ cả 2 bình.',
  },
  {
    id: 'role-hunter',
    name: 'Thợ săn',
    faction: 'village',
    icon: '🏹',
    isBuiltIn: true,
    actsAtNight: true,
    priority: 7,
    targetCount: 1,
    canTargetSelf: false,
    canTargetDead: true,
    effect: 'kill',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    skippable: true,
    description: 'Khi chết (đêm hoặc bị vote), được bắn 1 người khác chết theo.',
  },
  {
    id: 'role-halfwolf',
    name: 'Bán Sói',
    faction: 'village',
    icon: '🐾',
    isBuiltIn: true,
    actsAtNight: false,
    priority: 100,
    targetCount: 0,
    canTargetSelf: false,
    canTargetDead: false,
    effect: 'custom',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    skippable: false,
    turnsWolfOnBite: true,
    description: 'Nếu bị Sói cắn thì không chết mà biến thành Sói từ đêm sau. Nếu bị giết bởi chức năng khác (thuốc độc, Thợ săn, vote...) thì vẫn chết bình thường.',
  },
  {
    id: 'role-fool',
    name: 'Thằng Đần',
    faction: 'village',
    icon: '🃏',
    isBuiltIn: true,
    actsAtNight: false,
    priority: 100,
    targetCount: 0,
    canTargetSelf: false,
    canTargetDead: false,
    effect: 'custom',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    skippable: false,
    winsIfVotedOut: true,
    description: 'Nếu bị dân làng bỏ phiếu loại vào ban ngày thì thắng cả ván ngay lập tức.',
  },
  {
    id: 'role-elder',
    name: 'Già làng',
    faction: 'village',
    icon: '🧓',
    isBuiltIn: true,
    actsAtNight: false,
    priority: 99,
    targetCount: 0,
    canTargetSelf: false,
    canTargetDead: false,
    effect: 'custom',
    firstNightOnly: false,
    extraLives: 1,
    isCouncil: false,
    skippable: false,
    description: 'Có 2 mạng khi bị dân làng vote loại (vẫn chết ngay nếu bị Sói cắn hoặc thuốc độc).',
  },
  {
    id: 'role-villager',
    name: 'Dân thường',
    faction: 'village',
    icon: '🧑‍🌾',
    isBuiltIn: true,
    actsAtNight: false,
    priority: 101,
    targetCount: 0,
    canTargetSelf: false,
    canTargetDead: false,
    effect: 'custom',
    firstNightOnly: false,
    extraLives: 0,
    isCouncil: false,
    skippable: false,
    description: 'Không có khả năng đặc biệt — chỉ tham gia thảo luận và bỏ phiếu ban ngày.',
  },
]

export function cloneBuiltInRoles(): RoleDef[] {
  return BUILT_IN_ROLES.map((role) => ({ ...role }))
}

/**
 * Đồng bộ ván đã lưu (localStorage) với bộ vai trò mặc định mới nhất — vá cả
 * vai mới thêm sau này (VD Nguyệt Nữ, Bán Sói, Thằng Đần) lẫn field mới trên
 * vai cũ, trong khi vẫn giữ nguyên các vai trò tùy chỉnh MC đã tự tạo.
 */
export function syncBuiltInRoles(existingRoles: RoleDef[]): RoleDef[] {
  const customRoles = existingRoles.filter((r) => !r.isBuiltIn)
  return [...cloneBuiltInRoles(), ...customRoles]
}
